export default {
    ACTION_1: 'ACTION_1',
    TOGGLE_TREE: 'TOGGLE_TREE',
    CHANGE_VALUE: 'CHANGE_VALUE',
    SHUFFLE: 'SHUFFLE',
    UNSHUFFLE: 'UNSHUFFLE',
    DATA_FATCH_START: 'DATA_FATCH_START',
    DATA_FATCH_SUCCESS: 'DATA_FATCH_SUCCESS',
};